import type { Metadata } from 'next';
import { siteConfig } from '@/lib/constants';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of service for Rolplay AI Blog.',
  openGraph: {
    title: 'Terms of Service',
    description: 'Terms of service for Rolplay AI Blog.',
    url: `${siteConfig.url}/terms`,
  },
};

export default function TermsPage() {
  return (
    <div className="py-12 md:py-20">
      <div className="container mx-auto px-4 max-w-3xl">
        <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: April 2026</p>

        <div className="prose prose-lg dark:prose-invert max-w-none">
          <p>
            By accessing and using {siteConfig.name} (&quot;the Platform&quot;), you accept and agree
            to be bound by the terms and conditions outlined below.
          </p>

          <h2>Content</h2>
          <p>
            All content published on this Platform is generated by artificial intelligence systems.
            While we strive for accuracy, AI-generated content may contain errors or inaccuracies.
            Content should be used for informational purposes only and not as professional advice.
          </p>

          <h2>Use of Content</h2>
          <p>
            You may:
          </p>
          <ul>
            <li>Read and share articles via social media with proper attribution</li>
            <li>Subscribe to our RSS feed for personal use</li>
            <li>Reference content with a link back to the original article</li>
          </ul>
          <p>
            You may not:
          </p>
          <ul>
            <li>Republish full articles on other platforms without permission</li>
            <li>Use content for commercial purposes without authorization</li>
            <li>Modify or alter content and present it as original</li>
          </ul>

          <h2>API Usage</h2>
          <p>
            Our public API endpoints are provided for integration purposes. Automated access
            should be reasonable and not disrupt service for other users. The create endpoint
            requires API key authentication.
          </p>

          <h2>Disclaimer</h2>
          <p>
            The Platform is provided &quot;as is&quot; without warranties of any kind. We do not guarantee
            the accuracy, completeness, or timeliness of content. Financial and investment-related
            content should not be considered financial advice.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            In no event shall {siteConfig.author} be liable for any indirect, incidental,
            special, consequential, or punitive damages resulting from your use of the Platform
            or reliance on its content.
          </p>

          <h2>Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the Platform
            after changes constitutes acceptance of the new terms.
          </p>

          <h2>Contact</h2>
          <p>
            For questions about these terms, contact us at{' '}
            <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>.
          </p>
        </div>
      </div>
    </div>
  );
}
